// Generated by CoffeeScript 1.4.0
(function() {
  var Service, middleware, _;

  Service = require('./service');

  _ = require('underscore');

  middleware = function(options) {
    var service;
    Service.loadTemplates(options.rootPath, function(err, res) {
      if (err) {
        throw e;
      }
    });
    service = Service.make(options);
    process.on('exit', function() {
      return service.close();
    });
    return function(req, res, next) {
      var onSendMail;
      onSendMail = function(evt) {
        var args;
        args = _.extend({}, options.args, evt.args);
        console.log('onSendMail', args, evt);
        return service.send(args, evt.data, function() {});
      };
      res.on('sendMail', onSendMail);
      res.once('finish', function() {
        return res.removeListener('sendMail', onSendMail);
      });
      return next();
    };
  };

  module.exports = middleware;

}).call(this);
